spring.application.name=First

#Spring.application.name is a key and First is it's value
#Can write all configurations
#Just like ports and API's
#To modify the port use : "server.port=8081 or 8000"
#The database's proerties like connections username and passwords will be written here
#docs.spring.io/spring-boot/appendix/application-properties/inde.html
